### ISSUE TITLE
Require Core edition in module manifest

### ISSUE THREAD

**Issue by jdhitsolutions** [anthonyg-1/PSTcpIp#2]
If your module only works in PowerShell 7, I suggest you use the module manifest to specify that requirement.

**Comment by anthonyg-1** [comment]
Hi Jeff, thanks for the feedback. If memory serves me correctly, when I
made that a requirement in the module manifest it broke my Azure DevOps
build. I'll take a look at it again but the way I got around it was by
using the #requires -Version 7 statement in the psm1 file.

**Comment by jdhitsolutions** [comment]
You really need to find a way to specify in the manifest so that when people search the PowerShell Gallery they can filter accordingly.

**Comment by anthonyg-1** [comment]
Added the version to the manifest.
