### ISSUE TITLE
Add 5986 to port list

### ISSUE THREAD

**Issue by jdhitsolutions** [anthonyg-1/PSTcpIp#5]
I suggest adding port 5986 to your port list for WSMan SSL connections. Another option would be to add commands to the module to let the user manage `$tcpPortAndDescriptionData`.  I know I can do something like this:

```powershell
$tcpPortAndDescriptionData[5986] = "WinRM/SSL"
```

But it is always nicer to give the user a command.

**Comment by anthonyg-1** [comment]
Hi Jeff, I added port 5986 to the list. I'm not quite sure about adding a function to have the user manage the port list though. Can you elaborate as to what that may look like? Right now the user cannot add ports to the JSON file, but they can pass an array of ports to the Port parameter.

**Comment by jdhitsolutions** [comment]
I threw together some rough functions of what I had in mind.

```powershell
Function Set-TCPPortDescription {
    [CmdletBinding(SupportsShouldProcess)]
    Param(
        [Parameter(Position = 0, Mandatory)]
        [int32]$Port,
        [Parameter(Position = 1, Mandatory)]
        [string]$Description,
        [switch]$PassThru
    )

    if ($PSCmdlet.ShouldProcess("$port/$description")) {
        $global:tcpPortAndDescriptionData[$port] = $Description
        if ($PassThru) {
            Get-TCPPortDescription -Port $port
        }
    }
}

Function Remove-TCPPortDescription {
    [CmdletBinding(SupportsShouldProcess)]
    Param(
        [Parameter(Position = 0, Mandatory)]
        [int32]$Port
    )

    if ($PSCmdlet.ShouldProcess($port)) {
        $global:tcpPortAndDescriptionData.Remove($port)
    }
}

Function Get-TCPPortDescription {
    [CmdletBinding(SupportsShouldProcess)]
    Param(
        [Parameter(Position = 0)]
        [int32]$Port
    )

    if ($Port -AND $global:tcpPortAndDescriptionData.ContainsKey($port)) {
        [PSCustomObject]@{Port = $Port;Description = $global:tcpPortAndDescriptionData[$port]}
    }
    elseif ($Port -AND (-Not $global:tcpPortAndDescriptionData.ContainsKey($port))) {
        Write-Warning "Port $port not defined."
    }
    else {
        $global:tcpPortAndDescriptionData.GetEnumerator() | ForEach-Object { [PSCustomObject]@{Port = $_.Key;Description = $_.Value}}
    }
}
```

The idea is that a user might have a custom port. I know they can specify it, but if it isn't in your list, I don't think they get a description.

![image](https://github.com/anthonyg-1/PSTcpIp/assets/12089920/49edab8a-3191-4a55-a20d-2924ddcef071)

The user could use these functions to manage the port list after it has been imported. Nobody has to touch the JSON file, but you give the user flexibility.

**Comment by anthonyg-1** [comment]
I like it. I'll look at implementing this in a future version.
