### ISSUE TITLE
Format tcpConnectionStatus as autosized table

### ISSUE THREAD

**Issue by jdhitsolutions** [anthonyg-1/PSTcpIp#6]
This is a small thing, but it makes a big difference in usability. You can modify your formatting XML to create an auto-sized table.
Here is your default output:

![image](https://github.com/anthonyg-1/PSTcpIp/assets/12089920/ee681aa4-c06f-4e0c-8eef-c800cdf9cb4c)

And auto-sized.

![image](https://github.com/anthonyg-1/PSTcpIp/assets/12089920/c5e113c3-d3da-4411-973d-e92cbcaadc7f)

```xml
 <TableControl>
         <AutoSize />
        <TableHeaders>
```

**Comment by anthonyg-1** [comment]
Done. Will be in version 4.2.10.

**Comment by anthonyg-1** [comment]
Completed this change.
