### ISSUE TITLE
Use parallel option in Test-TCPConnection

### ISSUE THREAD

**Issue by jdhitsolutions** [anthonyg-1/PSTcpIp#7]
Because your module requires PowerShell 7, you should use `ForEach-Object -parallel` in `Test-TCPConnection` for performance. I tested with 4 machines, and it took over 1 minute. But using the parallel option only took 18 seconds. Yes, I know the user could run this:

```powershell
"srv1","srv2","dom1","srv3" | foreach-object -Parallel { Test-TcpConnection -HostName $_}
```

But you could make your command easier and faster by adding this internally so that this:

```powershell
Test-TcpConnection -HostName srv1,srv2,dom1,srv3
```

Runs just as quickly.

**Comment by anthonyg-1** [comment]
This is a heavier lift and will require some refactoring. Will explore this in a bit.

**Comment by jdhitsolutions** [comment]
I hope you don't feel I'm ganging up on you. On the contrary, you've got something good here that I'd like to help you improve.

**Comment by jdhitsolutions** [comment]
If you have questions on how you might refactor your code, I'm happy to help.

**Comment by anthonyg-1** [comment]
All good Jeff. I've used ForEach-Object -Parallel in a limited context but due to the nested loops (I wrote the original incarnation of this function over 10 years ago) I'm getting exceptions with ForEach-Object -Paralell so could definitely use some help with a refactor here.

**Comment by anthonyg-1** [comment]
...and this is something I definitely want to implement due to this function being extremely slow compared to nmap.

**Comment by anthonyg-1** [comment]
Hi Jeff, a colleague of mine and I reviewed this and tested various ForEach-Object -Parallel and we came to the conclusion that the variable scoping challenges with nested loops made this a non-starter without a rewrite. I'll explore that at some point but given the work to accomplish that I'm going to table this one for now. In short, the code got really messy really quickly with endless $using: statements everywhere.

**Comment by anthonyg-1** [comment]
The challenge is that I effectively would need ForEach-Object -Parallel to run for both the hosts and ports. I'll explore this over time but it's not clear to me at present as to how I would implement this.

**Comment by anthonyg-1** [comment]
Jeff, as far as refactoring, how would you approach this if one wanted to
parallelize both the values from the DNSHostName and Ports parameters? I
feel like this would much cleaner to code if I only had to focus on one of
those.

**Comment by jdhitsolutions** [comment]
I would run the test for each host in parallel. I don't think the overhead in testing ports in parallel is worth the effort. I can think of ways you *could* do it, but I don't think it is necessary.

**Comment by anthonyg-1** [comment]
That makes sense. Give me a week or so and I'll take a crack at implementing it that way.
