### ISSUE TITLE
Get-TLSInformation missing mandatory parameter

### ISSUE THREAD

**Issue by jdhitsolutions** [anthonyg-1/PSTcpIp#8]
I updated the module to 4.2.10, but `Get-TLSInformation` is missing a mandatory parameter.

![image](https://github.com/anthonyg-1/PSTcpIp/assets/12089920/d94bb87b-8598-49ab-bbfd-246b80a653cd)

**Comment by jdhitsolutions** [comment]
This is also true of `Get-TlsCertificate`

**Comment by anthonyg-1** [comment]
Hmm...I have parameters marked as mandatory for each of their respective
parameter sets as such:

 param(
        [Parameter(Mandatory = $true, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true, Position = 0, ParameterSetName = "HostName")][ValidateLength(1, 250)][Alias('ComputerName', 'IPAddress', 'Name', 'h', 'i')][String]$HostName,
        [Parameter(Mandatory = $false, ValueFromPipelineByPropertyName = $true, Position = 1, ParameterSetName = "HostName")][ValidateRange(1, 65535)][Alias('PortNumber', 'p')][Int]$Port = 443,
        [Parameter(Mandatory = $true, ValueFromPipelineByPropertyName = $true, Position = 0, ParameterSetName = "Uri")][Uri]$Uri,
        [Parameter(Mandatory = $false, Position = 2)][Switch]$IncludeChain
    )

Is there something else I could do here?

**Comment by anthonyg-1** [comment]
Never mind, got it. Need to set default parameter set. Doing that now.

**Comment by anthonyg-1** [comment]
Fixed in 4.2.11
